from django.urls import path

from .views import (
    CustomObtainAuthToken,
    ChangePassword,
    ResetPassword,
    CreateAccountAPIView,
    ProfileCreateAPIView,
    UsersProfileListAPIView,
    ProfileDetailsAPIView,
    ProfileUpdateAPIView,
    UpgradeUserAccountAPIView,
    CreateUpdateMarchantAccountAPIView,
    UpdateAccountToMarchantAPIView,
    MarchantCreateAPIView,
    MarchantListAPIView,
    MarchantDetailsAPIView,
    MarchantUpdateAPIView,
    MarchantDeleteAPIView,
    BranchListAPIView,
    SubscriptionPlanCreateAPIView,
    SubscriptionPlanListAPIView,
    SubscriptionPlanDetailsAPIView,
    SubscriptionPlanUpdateAPIView,
    SubscriptionPlanDeleteAPIView,
    #
    CastCreateAPIView,
    CastListAPIView,
    CastSearchAPIView,
    CastDetailsAPIView,
    CastUpdateAPIView,
    CastDeleteAPIView,
    
)

# from .authentication.views import CustomObtainAuthToken, ChangePassword
urlpatterns = [
    path("jwt/", CustomObtainAuthToken.as_view()),
    path("change-password/", ChangePassword.as_view()),
    path("reset-password/", ResetPassword.as_view()),
    path("create-user/", CreateAccountAPIView.as_view()),
    path("create/profile/", ProfileCreateAPIView.as_view()),
    path("list/profile/", UsersProfileListAPIView.as_view()),
    path("profile/details/<pk>/", ProfileDetailsAPIView.as_view()),
    path("profile/update/<pk>/", ProfileUpdateAPIView.as_view()),
    path("profile/upgrade-to-premium-user/", UpgradeUserAccountAPIView.as_view()),
    path("profile/create-update-marchant/", CreateUpdateMarchantAccountAPIView.as_view()),
    path("profile/upgrade-to-marchant/", UpdateAccountToMarchantAPIView.as_view()),
    path("marchant/create/", MarchantCreateAPIView.as_view()),
    path("marchant/list/", MarchantListAPIView.as_view()),
    path("marchant/details/<pk>/", MarchantDetailsAPIView.as_view()),
    path("marchant/update/<pk>/", MarchantUpdateAPIView.as_view()),
    path("marchant/delete/<pk>/", MarchantDeleteAPIView.as_view()),
    path("branch/list/", BranchListAPIView.as_view()),
    path("subscription-plan/create/", SubscriptionPlanCreateAPIView.as_view()),
    path("subscription-plan/list/", SubscriptionPlanListAPIView.as_view()),
    path("subscription-plan/details/<pk>/", SubscriptionPlanDetailsAPIView.as_view()),
    path("subscription-plan/update/<pk>/", SubscriptionPlanUpdateAPIView.as_view()),
    path("subscription-plan/delete/<pk>/", SubscriptionPlanDeleteAPIView.as_view()),
    #
    path("cast/create/", CastCreateAPIView.as_view()),
    path("cast/list/", CastListAPIView.as_view()),
    path("cast/search/", CastSearchAPIView.as_view()),
    path("cast/details/<pk>/", CastDetailsAPIView.as_view()),
    path("cast/update/<pk>/", CastUpdateAPIView.as_view()),
    path("cast/delete/<pk>/", CastDeleteAPIView.as_view()),
]
