# Generated by Django 3.2.8 on 2021-10-06 09:04

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to=accounts.models.marchant_image_location)),
                ('hq_address', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marchants', to='location.lga')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marchants', to='location.state')),
            ],
            options={
                'verbose_name': 'Marchant',
                'verbose_name_plural': 'Marchants',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.marchant')),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.lga')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.state')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['-updated', 'company'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(choices=[('free_user', 'Free User'), ('premium_user', 'Premium User'), ('marchant', 'marchant'), ('staff', 'Staff'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='free_user', max_length=50)),
                ('image', models.ImageField(upload_to=accounts.models.user_image_location)),
                ('surname', models.CharField(max_length=50)),
                ('other_names', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('DOB', models.DateField(help_text='Date of Birth')),
                ('address', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_staffs', to='accounts.store')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_staffs', to='accounts.marchant')),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='location.lga')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='location.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-updated', 'surname', 'other_names'],
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('balance', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('active', models.BooleanField(default=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'User Wallet',
                'verbose_name_plural': 'Users Walltes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
