# Generated by Django 3.2.8 on 2021-10-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('users', 'Users'), ('marchants', 'Marchants')], default='users', max_length=20),
        ),
    ]
