# Generated by Django 3.2.8 on 2021-10-18 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_subscriptionplan_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='marchant',
            name='plan',
            field=models.OneToOneField(blank=True, limit_choices_to=models.Q(('plan_type', 'marchants')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marchants', to='accounts.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='marchant',
            name='subscribtion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.OneToOneField(blank=True, limit_choices_to=models.Q(('plan_type', 'users')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscribtion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
