# Generated by Django 3.2.8 on 2021-10-22 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211018_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchant',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('plan_type', 'users')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.subscriptionplan'),
        ),
    ]
