# Generated by Django 3.2.8 on 2021-10-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211022_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchant',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
