# Generated by Django 3.2.8 on 2022-02-15 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettokens',
            name='expired_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
