# Generated by Django 3.2.8 on 2021-10-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonepisode',
            name='posters',
            field=models.ManyToManyField(blank=True, to='vod.Poster'),
        ),
        migrations.AlterField(
            model_name='seriesseason',
            name='posters',
            field=models.ManyToManyField(blank=True, to='vod.Poster'),
        ),
    ]
