# Generated by Django 3.2.8 on 2021-10-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0003_auto_20211014_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
