# Generated by Django 3.2.8 on 2021-10-15 09:34

import core.utils.units
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211015_0859'),
        ('vod', '0004_rename_genre_movie_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('uid', models.UUIDField(default=core.utils.units.LongUniqueId)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.store')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.marchant')),
            ],
            options={
                'verbose_name': 'Poster',
                'verbose_name_plural': 'Posters',
                'ordering': ['-updated'],
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='posters',
        ),
        migrations.RemoveField(
            model_name='seasonepisode',
            name='posters',
        ),
        migrations.RemoveField(
            model_name='series',
            name='posters',
        ),
        migrations.RemoveField(
            model_name='seriesseason',
            name='posters',
        ),
        migrations.DeleteModel(
            name='Poster',
        ),
        migrations.AddField(
            model_name='movieposter',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='vod.movie'),
        ),
    ]
