# Generated by Django 3.2.8 on 2021-10-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0007_comment_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_repr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='object representation'),
        ),
        migrations.AlterField(
            model_name='review',
            name='object_repr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='object representation'),
        ),
    ]
