# Generated by Django 3.2.8 on 2021-11-06 09:02

import core.utils.units
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vod', '0012_auto_20211104_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uid', models.SlugField(default=core.utils.units.LongUniqueId)),
                ('object_id', models.BigIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'vod'), ('model', 'movie')), models.Q(('app_label', 'vod'), ('model', 'series')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-updated'],
            },
        ),
    ]
