# Generated by Django 3.2.8 on 2021-11-06 09:18

import core.utils.units
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vod', '0013_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='promotions'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotion',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'vod'), ('model', 'movie')), models.Q(('app_label', 'vod'), ('model', 'series')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='object_id',
            field=models.BigIntegerField(verbose_name='PK of Movie or a Serie'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='uid',
            field=models.CharField(default=core.utils.units.getUniqueId, max_length=10, unique=True),
        ),
    ]
