# Generated by Django 3.2.8 on 2021-11-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0014_auto_20211106_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='object_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='PK of Movie or a Serie'),
        ),
    ]
