# Generated by Django 3.2.8 on 2021-11-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0015_alter_promotion_object_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='status',
            new_name='active',
        ),
        migrations.AddField(
            model_name='promotion',
            name='type',
            field=models.CharField(choices=[('poster', 'Poster'), ('movie', 'Movie'), ('series', 'Series')], default='poster', max_length=10),
            preserve_default=False,
        ),
    ]
