# Generated by Django 3.2.8 on 2021-11-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0016_auto_20211106_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='location',
            field=models.CharField(choices=[('main_home_slider', 'Main Home Slider'), ('home_slider', 'Home Slider'), ('breadcrumb_slider', 'Breadcrumb Slider'), ('login_page', 'Login Page')], default='main_home_slider', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='poster',
            field=models.ImageField(upload_to='promotions'),
        ),
    ]
