# Generated by Django 3.2.8 on 2021-11-08 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_subscriptionplan_duration'),
        ('vod', '0017_auto_20211108_1016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeasonEpisode',
            new_name='SeriesEpisode',
        ),
        migrations.AlterModelOptions(
            name='seriesepisode',
            options={'ordering': ['-timestamp', 'title'], 'verbose_name': 'Series Episode', 'verbose_name_plural': 'Series Episodes'},
        ),
        migrations.RemoveField(
            model_name='seriesepisode',
            name='season',
        ),
        migrations.AddField(
            model_name='seriesepisode',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='vod.series'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SeriesSeason',
        ),
    ]
