# Generated by Django 3.2.8 on 2021-11-08 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_subscriptionplan_duration'),
        ('vod', '0018_auto_20211108_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='access_level',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('exclusive', 'Exclusive')], default='free', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_series', to='accounts.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seriesepisode',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_episodes', to='accounts.userprofile'),
            preserve_default=False,
        ),
    ]
