# Generated by Django 3.2.8 on 2021-12-13 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vod', '0020_rename_genre_series_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='object_pk',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'vod'), ('model', 'movie')), models.Q(('app_label', 'vod'), ('model', 'series')), models.Q(('app_label', 'vod'), ('model', 'seriesepisode')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='PK of Movie, Serie or Series Episode'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='location',
            field=models.CharField(choices=[('main_home_slider', 'Main Home Slider'), ('home_slider', 'Home Slider'), ('breadcrumb_slider', 'Breadcrumb Slider'), ('login_page', 'Login Page'), ('movie_page', 'Movie Page'), ('series_page', 'Series Page')], max_length=50),
        ),
        migrations.AlterField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(blank=True, to='vod.Genre'),
        ),
    ]
