# Generated by Django 3.2.8 on 2022-02-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0024_auto_20220211_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(default=2021),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='running_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='release_year',
            field=models.PositiveIntegerField(default=2021),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='running_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
